#!/usr/bin/env bash

echo '{"version":1,"stop_signal":10,"cont_signal":12,"click_events":true}'
echo '[[]'

conky -c ~/.conkyrc -d

IFS="}"
while read;do
  IFS=" "
  parsed=`echo $REPLY | sed -e s/[{}]//g -e "s/ \"/\"/g" | awk '{n=split($0,a,","); for (i=1; i<=n; i++) {m=split(a[i],b,":"); if (b[1] == "\"name\"") {NAME=b[2]} if (b[1] =="\"x\"") {X=b[2]} if (b[1] =="\"y\"") {Y=b[2]} } print NAME " " X " " Y}'`
  read name x y <<< $parsed

  case "${name}" in
    \"calendar\")
      gsimplecal
      ;;
  esac

  IFS="}"
done
