#!/usr/bin/env bash
#
# Prints the name of the currently active window.
#
set -e

# TODO hack to avoid crashes due to malformed JSON
#      how can this be properly escaped?
name=`xdotool getactivewindow getwindowname | tr '\\' '/' | tr '"' "'"`

echo ${name}
