#!/usr/bin/env bash
#set -e

sudo pacman --noconfirm -S \
vim \
gcc \
make \
 \
conky \
i3lock \
gsimplecal \
 \
scrot \
feh \
acpi \
xdotool \
dmenu \
 \
rxvt-unicode \
 \
xcb-util-keysyms \
xcb-util-wm \
xcb-util-cursor \
yajl \
startup-notification \
libev \
 \
python3 \
python-pip
